apiVersion: v1
kind: Namespace
metadata:
  name: client-egress-test
  labels: {istio-injection: enabled}
---
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: client-egress-test
spec:
  egress:
  - hosts:
    - "istio-system/*"
    - "shared-ns/*"
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-client
  namespace: client-egress-test
  labels: {app: curl-client}
spec:
  containers:
  - name: curl
    image: curlimages/curl:8.16.0
    command: ["sleep", "infinity"]
