apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    serviceSettings:
      - settings:
          clusterLocal: true
        hosts:
          - "*"
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster1
      network: network1


