apiVersion: v1
kind: Namespace
metadata:
  name: spire-istio-client
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-client
  namespace: spire-istio-client
---
apiVersion: v1
kind: Pod
metadata:
  name: istio-client
  namespace: spire-istio-client
  labels:
    app: istio-client
    spiffe.io/spire-managed-identity: "true"
  annotations:
    inject.istio.io/templates: "sidecar,spire"
    proxy.istio.io/config: |
      customConfigFile: "/etc/istio/custom-bootstrap/custom_bootstrap_full.json"
spec:
  serviceAccountName: istio-client
  containers:
  - name: app
    image: curlimages/curl:8.16.0
    command: ["sleep", "infinity"]
